### ISSUE TITLE
$authorizeUrl

### ISSUE THREAD

**Issue by boinggg** [jmathai/foursquare-async#10]
The library has it as
https://foursquare.com/oauth/authorize
but foursquare says to use
https://foursquare.com/oauth2/authorize

Does it matter? Safe to change?

**Comment by jmathai** [comment]
Updating the authorizeurl to point to oauth2.
Closed by 5ef22eaf22a780657113b6e44ccd6f4fc719c0cc

**Comment by jmathai** [comment]
Thanks for reporting.
