### ISSUE TITLE
getAccessToken

### ISSUE THREAD

**Issue by boinggg** [jmathai/foursquare-async#11]
getAccessToken is adding a second ? and client_id and client_secret to the URL before it curls it.

**Comment by jmathai** [comment]
I believe this was fixed by this commit:
https://github.com/jmathai/foursquare-async/commit/ee2d725335e546f52f23448391a306a63678c391

Please reopen if not.

**Comment by boinggg** [comment]
Looks like it, when will the master download be fixed with all these changes?

**Comment by jmathai** [comment]
All bugs which are closed on github are in master.
