### ISSUE TITLE
Could someone add this?

### ISSUE THREAD

**Issue by boinggg** [jmathai/foursquare-async#12]

**Comment by boinggg** [comment]
protected $userAgent      = 'EpiFoursquare (http://github.com/jmathai/foursquare-async/tree/)';

  public function setUserAgent($uagent = null)  {
    if($uagent !== null)
      $this->userAgent = $uagent;
      //print $this->userAgent;
  }

```
curl_setopt($ch, CURLOPT_USERAGENT, $this->userAgent);
```

example
  $fsObj = new EpiFoursquare($clientId, $clientSecret);
  $fsObj->setUserAgent($_SERVER['HTTP_USER_AGENT']);

**Comment by jmathai** [comment]
Allowing user agent to be overridden and actually using it in the request.
Closed by f0801e04f55e890a360c70bfeb12191429b7ae1e

**Comment by jmathai** [comment]
Fixed.
