### ISSUE TITLE
Seems to be timing out when calling getAccessToken?

### ISSUE THREAD

**Issue by cwhittl** [jmathai/foursquare-async#18]
I've taken the original sample test and tried to put our credentials in it and it times out when trying to get the access token.. Here is my stripped down version sans credentials.

<?php
ob_start();
require_once 'EpiCurl.php';
require_once 'EpiFoursquare.php';
$clientId = '';
$clientSecret = '';
$redirectUri = 'http://collectivebias.com/sites/desertmonkey/foursquare/index.php';
$userId = '';
$fsObj = new EpiFoursquare($clientId, $clientSecret, $accessToken);
$fsObjUnAuth = new EpiFoursquare($clientId, $clientSecret);
?>

<script type="text/javascript">
function viewSource() {
    document.getElementById("source").style.display = "block";
}
</script>

<h1>Simple test to make sure everything works ok</h1>

<h2><a href="javascript:void(0);" onclick="viewSource();">View the source of this file</a></h2>

<div id="source" style="display:none; padding:5px; border: dotted 1px #bbb; background-color:#ddd;">
<?php highlight_file(__FILE__); ?>
</div>

<hr>

<?php if(!isset($_GET['code']) && !isset($_COOKIE['access_token'])) { ?>

<h2>Generate the authorization link</h2>

<?php $authorizeUrl = $fsObjUnAuth->getAuthorizeUrl($redirectUri); ?>
<a href="<?php echo $authorizeUrl; ?>"><?php echo $authorizeUrl; ?></a>

<?php } else { ?>
    <h2>Display your own badges</h2>
    <?php
    if(!isset($_COOKIE['access_token'])) {
        $token = $fsObjUnAuth->getAccessToken($_GET['code'], $redirectUri);
        setcookie('access_token', $token->access_token);
        $_COOKIE['access_token'] = $token->access_token;
    }
    $fsObjUnAuth->setAccessToken($_COOKIE['access_token']);
    ?>
<?php } ?>

<hr>

**Comment by jmathai** [comment]
Can you try to comment out lines 170 and 171 in EpiOAuth.php?

On May 2, 2011 4:38 PM, "cwhittl" <
reply@reply.github.com>
wrote:

**Comment by cwhittl** [comment]
That file is not included in the implementation I downloaded...
EpiCurl,EpiFourSquare,EpiSequence are the only ones...

**Comment by cwhittl** [comment]
That file is not included in the implementation I downloaded...
EpiCurl,EpiFourSquare,EpiSequence are the only ones...

**Comment by jmathai** [comment]
Alright. Wrong library :). I will have a look once I have access to my
computer.

On May 2, 2011 4:56 PM, "cwhittl" <
reply@reply.github.com>
wrote:

**Comment by cwhittl** [comment]
Looks like it's curl_setopt($ch, CURLOPT_INTERFACE, $_SERVER ['SERVER_ADDR']);
Does this need to be set somewhere for GoDaddy?  If I comment it out it works fine...

**Comment by jmathai** [comment]
Yes, it's those two lines. Comment them out and see if they work.

It's the same problem (but in a different file) in the corresponding Twitter library.

Please reopen if that doesn't solve the problem.

**Comment by jcorry** [comment]
I'm having the same issue, commented out the CURLOPT_INTERFACE line and it's still not working.

httpd goes to 90% CPU usage, MBP fans all come on high and the page never loads.

php.ini looks like: 

cURL support    enabled
cURL Information    7.21.4
Age 3
Features
AsynchDNS   Yes
Debug   No
GSS-Negotiate   Yes
IDN No
IPv6    Yes
Largefile   Yes
NTLM    Yes
SPNEGO  No
SSL Yes
SSPI    No
krb4    No
libz    Yes
CharConv    No
Protocols   dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smtp, smtps, telnet, tftp
Host    universal-apple-darwin11.0
SSL Version OpenSSL/0.9.8r
ZLib Version    1.2.5

Why doesn't it work?

**Comment by jmathai** [comment]
@jcorry did you try the solution mentioned above?

**Comment by jcorry** [comment]
You mean this: 

> Yes, it's those two lines. Comment them out and see if they work.

I commented out this line:
if(isset($_SERVER['SERVER_ADDR']) && !empty($_SERVER['SERVER_ADDR']) && $_SERVER['SERVER_ADDR'] != '127.0.0.1')
        //curl_setopt($ch, CURLOPT_INTERFACE, $_SERVER ['SERVER_ADDR']);

**Comment by imka** [comment]
I am having the same problem and commenting out those two lines didn't work out for me. Has anyone found any solution?

**Comment by jcorry** [comment]
I did, it had no effect on my problem. I did discover that it works on one computer/network...but not on another. Even when it's the same ISP.

**Comment by jmathai** [comment]
@jcorry can you provide information on what's different between the two machines you used? OS, PHP version, curl version, etc.
