### ISSUE TITLE
Support synchrounous calls via curl_exec

### ISSUE THREAD

**Issue by therealpecus** [jmathai/foursquare-async#19]
Due to bugs in the current implementation of multi_curl on windows stacks, please port to foursquare-async the fixes for issues https://github.com/jmathai/twitter-async/issues/84 and https://github.com/jmathai/twitter-async/issues/88

**Comment by jmathai** [comment]
Mind verifying if the code in branch issue-19 works on Windows?

**Comment by therealpecus** [comment]
issue-19 code works beautifully.
