### ISSUE TITLE
Basic example does not work

### ISSUE THREAD

**Issue by pascalaschwanden** [jmathai/foursquare-async#25]
$twitterObj = new EpiTwitter(
    Hidden::TWITTER_CONSUMER_KEY,
    Hidden::TWITTER_CONSUMER_SECRET,
    $oauth_token,
    $oauth_token_secret);

$twitterObj->useAsynchronous(true);

//  neither one of the following work, and I've tried many many variations
$results = $twitterObj->get("users/lookup", array("user_id" => 2344));
$creds = $twitterObj->get('/account/verify_credentials.json');

echo $creds->responseText;
exit;

The result is that the process just hangs, or sometimes the whole server hangs :(
Sometimes it throughs an exception and I get error_code=0 with no error message.

I know the authentication is correct because it works just fine with other twitter libraries.

**Comment by jmathai** [comment]
Are you sure you're opening this issue against the correct repo? This is foursquare-async.

**Comment by pascalaschwanden** [comment]
sorry. wrong repo.  it's supposed to be the twitter-async repo.
