### ISSUE TITLE
Create get/set methods for user-agent

### ISSUE THREAD

**Issue by nedwidek** [jmathai/foursquare-async#5]
From: http://groups.google.com/group/foursquare-api/web/api-documentation

> Set your User-Agent header to something identifiable. Default identifiers like "Mozilla" or "libwww-perl/5.808" may get banned from time to time because of rate limits.

Directly editing EpiFoursquare.php creates the issue of having to redo the change when an update is applied. 

Here is what I added to my file, right above the OAUTH methods:

>  /\* House keeping methods */
>  public function setUserAgent($userAgent) {
>    $this->userAgent = $userAgent;
>  }
> 
>  public function getUserAgent() {
>    return $this->userAgent;
>  }

I looked at adding the ability to set this with the constructor, but that would be too problematic. Get/set methods are easy enough.

**Comment by boinggg** [comment]
dont u need
curl_setopt($ch, CURLOPT_USERAGENT, $userAgent);

**Comment by nedwidek** [comment]
The version I was referring to did not use curl, it set the user agent header directly on each call. The new version does not actually change the curl user agent at all. This means that the $userAgent variable is going unused and requests are being made with the default curl user agent.

**Comment by jmathai** [comment]
Closed this in another bug.
https://github.com/jmathai/foursquare-async/issues/closed#issue/12

<code>$fsObj->setUserAgent('My User Agent');</code>
