### ISSUE TITLE
API v2 not currently supported

### ISSUE THREAD

**Issue by fmalk** [jmathai/foursquare-async#6]
Foursquare is making a move in favor of their next OAuth2 API version. Current OAuth is going to be deprecated in mid-2011, just a few months away.
Are you planning to upgrade foursquare-async to support it? I'm not sure I can upgrade it myself. Currently I didn't find any suitable libraries which support it.

**Comment by kisPocok** [comment]
Same here. Are you planning to upgrade this?

**Comment by jmathai** [comment]
Upgraded. Documentation is available here https://github.com/jmathai/foursquare-async/wiki

**Comment by kisPocok** [comment]
Thanks a lot! Just in time :)

**Comment by sbourke** [comment]
Wow thanks

**Comment by fmalk** [comment]
Tested and it works like a charm. Thanks for updating it, jmathai!
