### ISSUE TITLE
getAccessToken() building malformed query string (Fix Included)

### ISSUE THREAD

**Issue by johnnytomcat** [jmathai/foursquare-async#8]
public function getAccessToken($code, $redirectUri)
  {
    $params = array('client_id' => $this->clientId, 'client_secret' => $this->clientSecret, 'grant_type' => 'authorization_code', 'redirect_uri' => $redirectUri, 'code' => $code);
    $qs = http_build_query($params);
    return $this->request('GET', "{$this->accessTokenUrl}?{$qs}");
  }
# Fix

public function getAccessToken($code, $redirectUri)
  {
    $params = array('client_id' => $this->clientId, 'client_secret' => $this->clientSecret, 'grant_type' => 'authorization_code', 'redirect_uri' => $redirectUri, 'code' => $code);
    $qs = http_build_query($params);
    return $this->request('GET', "{$this->accessTokenUrl}", $params); //line to change
  }

**Comment by alexey-detr-aksilon** [comment]
Thanks for this fix. It really helps me with 'invalid_grant' issue.

**Comment by pengas** [comment]
thanks dude, you should upload this fix.. just spend an hour trying to figure out what's what.

cheers,

~nir.

**Comment by johnnytomcat** [comment]
I have uploaded this fix.

**Comment by ryanhowdy** [comment]
thanks johnnytomcat
